metrics:
  - filename: "multiqc_picard_HsMetrics.txt"
    qc_col: "PCT_TARGET_BASES_20X"
    threshold: 0.945
    operator: "<="
    report_cols: ["Sample", "PCT_TARGET_BASES_20X"]
    sample_cols: ["Sample"]
    title: "Coverage"
  - filename: "multiqc_verifybamid.txt"
    qc_col: "FREEMIX"
    threshold: 0.04
    operator: ">"
    report_cols: ["Sample", "FREEMIX"]
    sample_cols: ["Sample"]
    title: "Contamination"
  - filename: ".*.kinship_check.out$"
    qc_col: "status"
    threshold: "FAIL"
    operator: "=="
    # special report_cols '@all' to select all columns.
    report_cols: "@all"
    sample_cols: ["sample_1", "sample_2"]
    comment: "#"
    title: "Kinship"
  - filename: ".*gendercheck.txt$"
    qc_col: "status"
    threshold: "FAIL"
    operator: "=="
    report_cols: ["sample_id", "test_gender", "true_gender"]
    sample_cols: ["sample_id"]
    title: "GenderCheck"
