metrics:
  - filename: "multiqc_picard_HsMetrics.txt"
    qc_col: "PCT_TARGET_BASES_20X"
    threshold: 0.99
    operator: "<="
    # special report_cols '@all' to select all columns.
    report_cols: ["Sample", "PCT_TARGET_BASES_20X"]
    title: "Coverage"
  - filename: "multiqc_verifybamid.txt"
    qc_col: "FREEMIX"
    threshold: 0.000002
    operator: ">"
    report_cols: ["Sample", "FREEMIX"]
    title: "Contamination"
  - filename: ".*.kinship_check.out$"
    qc_col: "status"
    threshold: "FAIL"
    operator: "=="
    report_cols: '@all'
    comment: "#"
    title: "Kinship"